version: '3'

services:

  producer:
    container_name: 'producer'
    build:
      context: ./
      dockerfile: producer/Dockerfile
    volumes:
      - ./producer:/src
    ports:
      - "8080:8080"
    networks:
      - app-network
    environment:
      - URL_RABBIT=amqp://rabbitmq
      - NODE_ENV=local_devel
      - PORT_EXPRESS=8080
    depends_on:
      - rabbitmq

  consumer:
    container_name: 'consumer'
    build:
      context: ./
      dockerfile: consumer/Dockerfile
    volumes:
      - ./consumer:/src
      - ./consumer/logs:/src/logs
    networks:
      - app-network
    environment:
      - URL_RABBIT=amqp://rabbitmq
      - NODE_ENV=local_devel
      - PATH_LOGS_SUCCESS=/src/logs/logsSuccess.log
      - PATH_LOGS_ERROR=/src/logs/logsError.log
    depends_on:
      - rabbitmq
      - producer

  rabbitmq:
    container_name: 'rabbitmq'
    image: rabbitmq:3-management
    hostname: "rabbitmq"
    labels:
      NAME: "rabbitmq"
    ports:
      - "15672:15672"
      - "5672:5672"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge